### ISSUE TITLE
bad result 

### ISSUE THREAD

**Issue by Patickk** [smallcorgi/3D-Deepbox#19]
thank you so much for your code! 
but, I wrote some code to visualize, the Orientation result is bad.  I test my code on the label of kitti , its good.
so,  if you have time , 
would you please explain your anchors code part?

**Comment by lyreoferato** [comment]
Check the data_processing/parse_annotation function.
The trained orientation is incorrect. In the Kitti dataset, alpha is the relative orientation between object and the camera.
The one you need to train is rotation_y, which is the last value of each label data.

**Comment by smallcorgi** [comment]
Hi all,
You can try my demo model.

Thanks
