### ISSUE TITLE
the result is bad

### ISSUE THREAD

**Issue by Ben940315** [smallcorgi/3D-Deepbox#23]
HI , I run the demo by :
python main.py --mode train --gpu 0 --image training/image_2/ --label training/label_2/ --box2d training/label_2/
 python main.py --mode test --gpu 0 --image  training/image_2/ --box2d training/label_2/ --model model/model-10 --output out/
 run run_demo.m

And I got the bad result,why?

**Comment by smallcorgi** [comment]
Hi @Ben940315,
You can try my demo model.

Thanks
