### ISSUE TITLE
A Bad Result

### ISSUE THREAD

**Issue by shengtao96** [smallcorgi/3D-Deepbox#5]
I'm sorry that I follow your instructions and get a bad result on the train/val data.

**Comment by smallcorgi** [comment]
Hi @shengtao96,
 
Sorry, there are some bugs in data processing.
Please clone new repository and train it again. 

Thanks,

**Comment by shengtao96** [comment]
After updating the code, the result is still bad.

**Comment by smallcorgi** [comment]
Hi @shengtao96,
 
I had retrained the Deep3DBox only 20 epochs and evaluated the AP of orientation.

The following table is the result , I think it is not bad.


                       Easy .      Moderate         Hard
Car               98.75%        96.42% .      92.92%
Pedestrian   65.12%        64.11% .      63.98%
Cyclist          77.5%          75.46%        72.95%

You can check the label format of dataset.
