### ISSUE TITLE
Cannot test the output. Model is not trained proper I guess.

### ISSUE THREAD

**Issue by abramjos** [smallcorgi/3D-Deepbox#6]
I used this code to test the 3d bounding box. Its showing some  TensorSliceReader  error.
`python main.py --mode test --gpu 00:1e.0 --image training/image_2/ --box2d training/label_2/ --model model/ --output out/`

```
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model/
	 [[Node: save/RestoreV2_37 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_37/tensor_names, save/RestoreV2_37/shape_and_slices)]]
	 [[Node: save/RestoreV2_17/_43 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_122_save/RestoreV2_17", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

Here is my model folder:
checkpoint                    model-5.data-00000-of-00001
model-10.data-00000-of-00001  model-5.index
model-10.index                model-5.meta
model-10.meta  

I should say that I changed main.py to change no of the epoch to 10 only.

**Comment by smallcorgi** [comment]
Hi @Abramjos ,

Please using following command line to test your model. 
python main.py --mode test --gpu 0 --image training/image_2/ --box2d training/label_2/ --model model/model-10 --output out/

**Comment by Abramjos** [comment]
Thanks, man. It worked. I got the labels as text files and I am trying to figure out how to get bounding 3D boxes from that data. All I get is a 15 field data like kitti but I dont know how to get 3D coordinates fr om that. Can you help with that?
example text file::
```
Misc 0.00 0 -1.71118731896 804.79 167.34 995.43 327.94 1.5194464986 1.64908124578 2.9650145342 3.23 1.59 8.55 -1.34998356347 0.822426
Car 0.00 0 -1.67641753803 657.39 190.13 700.07 223.39 1.5484387785 1.64252891487 3.89601439809 3.18 2.27 34.38 -1.58418433557 0.95983
```
I could make 2d box out of this `657.39 190.13 700.07 223.39` discarding the decimals.
what about 3d boxes?

**Comment by smallcorgi** [comment]
Please refers the object detection's format of KITTI dataset.

#Values    Name      Description
----------------------------------------------------------------------------
   1    type         Describes the type of object: 'Car', 'Van', 'Truck',
                     'Pedestrian', 'Person_sitting', 'Cyclist', 'Tram',
                     'Misc' or 'DontCare'
   1    truncated    Float from 0 (non-truncated) to 1 (truncated), where
                     truncated refers to the object leaving image boundaries
   1    occluded     Integer (0,1,2,3) indicating occlusion state:
                     0 = fully visible, 1 = partly occluded
                     2 = largely occluded, 3 = unknown
   1    alpha        Observation angle of object, ranging [-pi..pi]
   4    bbox         2D bounding box of object in the image (0-based index):
                     contains left, top, right, bottom pixel coordinates
   3    dimensions   3D object dimensions: height, width, length (in meters)
   3    location     3D object location x,y,z in camera coordinates (in meters)
   1    rotation_y   Rotation ry around Y-axis in camera coordinates [-pi..pi]
   1    score        Only for results: Float, indicating confidence in
                     detection, needed for p/r curves, higher is better.

**Comment by jediofgever** [comment]
@smallcorgi , hi
Unfourtunately I dont have a gpu to train this network, can you share trained model ? 
Thank you!

**Comment by smallcorgi** [comment]
Hi @jediofgever ,

Sorry, I could not share the trained model, because I trained the model by company's computer, and company could not use cloud storage.

**Comment by shichaoy** [comment]
hi, @smallcorgi 

For new data without 3d box txt, can the model predict the box locations given 2d box? I think this is another part of the paper. Have you implemented that?

**Comment by smallcorgi** [comment]
Hi @shichaoy,

You can refer issues #8.
