### ISSUE TITLE
Where does the location value(x, y, z) come from?

### ISSUE THREAD

**Issue by e2sh83** [smallcorgi/3D-Deepbox#8]
Hi,

I am wondering how you get the location value(3D object location x,y,z) which are necessary for 3D box calculation.
Do you suppose the location_x, location_y, and location_z are already regressed in 2D detector? It seems 3D location values are just read from 2D txt file according to your source code. 
Please make me right if I misunderstood.

**Comment by smallcorgi** [comment]
Hi @e2sh83 ,

In this project, I didn't implement the paper proposed "Correspondence Constraints".
If you want to get the location value (3D object location x,y,z), you can see the method of paper's supplementary materials.
They had some assumptions and used SVD decomposition to get the 3D object location.

**Comment by e2sh83** [comment]
Hi @smallcorgi,
Thank you for your answer!!

**Comment by lucasjinreal** [comment]
@smallcorgi Hi, if this not implement, then how to predict 3d box? Assuming that point is the center of 2d bouding box?

**Comment by patrick-llgc** [comment]
Hi I found someone else implemented the 2D/3D tight constraint based optimization to get the 3D location. 

https://github.com/lzccccc/3d-bounding-box-estimation-for-autonomous-driving/blob/master/utils/correspondece_constraint.py
